var child = [
  { 'dupe': false, 'type': 64, 'name': 'amount=1', 'dir': 'c0', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:from=6&balance=100&to=1&amount=1', 'fetched': true, 'code': 200, 'len': 140, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 2, 0, 0, 3, 0 ], 'sig': 0xf43316e7 },
  { 'dupe': false, 'type': 64, 'name': 'balance=100', 'dir': 'c1', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:from=6&balance=100&to=1&amount=1', 'fetched': true, 'code': 200, 'len': 140, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0x1976d459 },
  { 'dupe': false, 'type': 64, 'name': 'from=6', 'dir': 'c2', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:from=6&balance=100&to=1&amount=1', 'fetched': true, 'code': 200, 'len': 140, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0xcffbb89d },
  { 'dupe': false, 'type': 64, 'name': 'mail=skipfish@example.com', 'dir': 'c3', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:username=Smith&mail=skipfish@example.com&password=skipfish&rpassword=skipfish', 'fetched': true, 'code': 200, 'len': 1494, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 3, 1 ], 'sig': 0x60a4f22e },
  { 'dupe': false, 'type': 64, 'name': 'password=skipfish', 'dir': 'c4', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:username=Smith&mail=skipfish@example.com&password=skipfish&rpassword=skipfish', 'fetched': true, 'code': 200, 'len': 1494, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 1, 0 ], 'sig': 0xa56a9d39 },
  { 'dupe': false, 'type': 64, 'name': 'rpassword=skipfish', 'dir': 'c5', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:username=Smith&mail=skipfish@example.com&password=skipfish&rpassword=skipfish', 'fetched': true, 'code': 200, 'len': 1494, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0x532926f4 },
  { 'dupe': false, 'type': 64, 'name': 'to=1', 'dir': 'c6', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:from=6&balance=100&to=1&amount=1', 'fetched': true, 'code': 200, 'len': 140, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0xf5c5e75b },
  { 'dupe': false, 'type': 64, 'name': 'username=Smith', 'dir': 'c7', 'linked': 5, 'url': 'http://127.0.0.1/register.php DATA:username=Smith&mail=skipfish@example.com&password=skipfish&rpassword=skipfish', 'fetched': true, 'code': 200, 'len': 1494, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 3, 1 ], 'sig': 0xb7ed1c33 }
];
