var child = [
  { 'dupe': false, 'type': 4, 'name': 'resources', 'dir': 'c0', 'linked': 2, 'url': 'http://127.0.0.1/resources/resources/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'confirm.html', 'dir': 'c1', 'linked': 2, 'url': 'http://127.0.0.1/resources/confirm.html', 'fetched': true, 'code': 200, 'len': 958, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 0, 0 ], 'sig': 0xfff5dc12 },
  { 'dupe': false, 'type': 8, 'name': 'hello.html', 'dir': 'c2', 'linked': 5, 'url': 'http://127.0.0.1/resources/hello.html', 'fetched': true, 'code': 200, 'len': 856, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 5, 0, 1, 0, 0 ], 'sig': 0x782bd790 },
  { 'dupe': false, 'type': 8, 'name': 'login.html', 'dir': 'c3', 'linked': 2, 'url': 'http://127.0.0.1/resources/login.html', 'fetched': true, 'code': 200, 'len': 1454, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xfff5871a },
  { 'dupe': false, 'type': 8, 'name': 'logo.png', 'dir': 'c4', 'linked': 2, 'url': 'http://127.0.0.1/resources/logo.png', 'fetched': true, 'code': 200, 'len': 18602, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'reset.html', 'dir': 'c5', 'linked': 2, 'url': 'http://127.0.0.1/resources/reset.html', 'fetched': true, 'code': 200, 'len': 626, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 0, 0 ], 'sig': 0xfff5dc12 },
  { 'dupe': false, 'type': 8, 'name': 'styles.css', 'dir': 'c6', 'linked': 2, 'url': 'http://127.0.0.1/resources/styles.css', 'fetched': true, 'code': 200, 'len': 741, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'transaction.html', 'dir': 'c7', 'linked': 2, 'url': 'http://127.0.0.1/resources/transaction.html', 'fetched': true, 'code': 200, 'len': 73, 'decl_mime': 'text/html', 'sniff_mime': 'text/xml', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0x5adccbfe },
  { 'dupe': false, 'type': 32, 'name': 'login.php', 'dir': 'c8', 'linked': 5, 'url': 'http://127.0.0.1/resources/login.php', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'register.php', 'dir': 'c9', 'linked': 5, 'url': 'http://127.0.0.1/resources/register.php', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'reset.php', 'dir': 'c10', 'linked': 5, 'url': 'http://127.0.0.1/resources/reset.php', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'send.php', 'dir': 'c12', 'linked': 5, 'url': 'http://127.0.0.1/resources/send.php', 'fetched': true, 'code': 404, 'len': 1150, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x633bc7f0 },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c13', 'linked': 2, 'url': 'http://127.0.0.1/resources/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2166, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c14', 'linked': 2, 'url': 'http://127.0.0.1/resources/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2166, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
